-- 更多锚点 (10 条)
INSERT INTO anchors (id, creator_id, modality, text_content, topics, source, quality_score) VALUES ('a006', (SELECT id FROM users WHERE phone_hash='hash_night'), 'text', '加班到凌晨两点，走出写字楼，发现整条街只有路灯和我。打了辆车，司机问我这么晚下班啊。我说嗯。其实我也不想这么晚。', '["职场","加班","孤独"]', 'user', 0.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO anchors (id, creator_id, modality, text_content, topics, source, quality_score) VALUES ('a007', (SELECT id FROM users WHERE phone_hash='hash_dawn'), 'text', '分手那天没有争吵，只是她说我们不合适。我点了点头，好像早就知道。后来才明白，不合适是最温柔的告别。', '["爱情","分手","释然"]', 'user', 0.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO anchors (id, creator_id, modality, text_content, topics, source, quality_score) VALUES ('a008', (SELECT id FROM users WHERE phone_hash='hash_wind'), 'text', '在北京租房五年，搬了四次家。每次都以为是最后一次。现在又在看房了。', '["城市","租房","漂泊"]', 'user', 0.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO anchors (id, creator_id, modality, text_content, topics, source, quality_score) VALUES ('a009', (SELECT id FROM users WHERE phone_hash='hash_autumn'), 'text', '深夜戴上耳机，随机播放到一首老歌。旋律响起的瞬间，眼泪就下来了。不是因为歌好听，是因为想起了听这首歌时的自己。', '["音乐","回忆","情感"]', 'user', 0.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO anchors (id, creator_id, modality, text_content, topics, source, quality_score) VALUES ('a010', (SELECT id FROM users WHERE phone_hash='hash_winter'), 'text', '一个人去了趟海边，坐在沙滩上看日落。海浪声很大，心里却很安静。有些声音，是用来安静的。', '["旅行","海边","独处"]', 'user', 0.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO anchors (id, creator_id, modality, text_content, topics, source, quality_score) VALUES ('a011', (SELECT id FROM users WHERE phone_hash='hash_night'), 'text', '读完百年孤独，合上书，沉默了很久。有些故事，读完才知道自己有多幸运。孤独不可怕，可怕的是习惯了孤独。', '["阅读","百年孤独","感悟"]', 'user', 0.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO anchors (id, creator_id, modality, text_content, topics, source, quality_score) VALUES ('a012', (SELECT id FROM users WHERE phone_hash='hash_dawn'), 'text', '深夜煮了一碗泡面，加了个蛋。这大概是一天里最幸福的三分钟。吃完继续加班。', '["美食","深夜","简单"]', 'user', 0.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO anchors (id, creator_id, modality, text_content, topics, source, quality_score) VALUES ('a013', (SELECT id FROM users WHERE phone_hash='hash_wind'), 'text', '看到一个外卖小哥在雨中跑，突然觉得，每个人都在为生活奔跑。我也是。', '["社会","外卖","生活"]', 'user', 0.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO anchors (id, creator_id, modality, text_content, topics, source, quality_score) VALUES ('a014', (SELECT id FROM users WHERE phone_hash='hash_autumn'), 'text', '失眠了，盯着天花板。脑子里全是明天的事。但此刻，我只想安静地躺一会儿。明天的事，明天再说。', '["深夜","失眠","焦虑"]', 'user', 0.4) ON CONFLICT (id) DO NOTHING;
INSERT INTO anchors (id, creator_id, modality, text_content, topics, source, quality_score) VALUES ('a015', (SELECT id FROM users WHERE phone_hash='hash_winter'), 'text', '手机内存又满了，删了几个App，突然发现，有些App删了就没再装回来。人也一样。', '["科技","手机","关系"]', 'user', 0.4) ON CONFLICT (id) DO NOTHING;

-- 更多反应 (每锚点 3-5 条)
INSERT INTO reactions (user_id, anchor_id, reaction_type, emotion_word, modality, text_content, resonance_value) VALUES ((SELECT id FROM users WHERE phone_hash='hash_dawn'), 'a006', 'resonance', 'empathy', 'text', '加班的苦我懂', 0.8);
INSERT INTO reactions (user_id, anchor_id, reaction_type, emotion_word, modality, text_content, resonance_value) VALUES ((SELECT id FROM users WHERE phone_hash='hash_wind'), 'a006', 'neutral', NULL, 'text', '确实很辛苦', 0.4);
INSERT INTO reactions (user_id, anchor_id, reaction_type, emotion_word, modality, text_content, resonance_value) VALUES ((SELECT id FROM users WHERE phone_hash='hash_dawn'), 'a007', 'resonance', 'shock', 'text', '分手的痛我懂', 0.9);
INSERT INTO reactions (user_id, anchor_id, reaction_type, emotion_word, modality, text_content, resonance_value) VALUES ((SELECT id FROM users WHERE phone_hash='hash_wind'), 'a007', 'resonance', 'trigger', 'text', '让我想起了我的', 0.85);
INSERT INTO reactions (user_id, anchor_id, reaction_type, emotion_word, modality, text_content, resonance_value) VALUES ((SELECT id FROM users WHERE phone_hash='hash_autumn'), 'a008', 'resonance', 'empathy', 'text', '租房确实不容易', 0.75);
INSERT INTO reactions (user_id, anchor_id, reaction_type, emotion_word, modality, text_content, resonance_value) VALUES ((SELECT id FROM users WHERE phone_hash='hash_winter'), 'a008', 'opposition', NULL, 'text', '租房也有好处', 0.3);
INSERT INTO reactions (user_id, anchor_id, reaction_type, emotion_word, modality, text_content, resonance_value) VALUES ((SELECT id FROM users WHERE phone_hash='hash_night'), 'a009', 'resonance', 'shock', 'text', '音乐总能勾起回忆', 0.88);
INSERT INTO reactions (user_id, anchor_id, reaction_type, emotion_word, modality, text_content, resonance_value) VALUES ((SELECT id FROM users WHERE phone_hash='hash_dawn'), 'a009', 'resonance', 'trigger', 'text', '这首歌我也听过', 0.82);
INSERT INTO reactions (user_id, anchor_id, reaction_type, emotion_word, modality, text_content, resonance_value) VALUES ((SELECT id FROM users WHERE phone_hash='hash_wind'), 'a010', 'resonance', 'insight', 'text', '海边真的很治愈', 0.87);
INSERT INTO reactions (user_id, anchor_id, reaction_type, emotion_word, modality, text_content, resonance_value) VALUES ((SELECT id FROM users WHERE phone_hash='hash_autumn'), 'a011', 'resonance', 'empathy', 'text', '这本书我也读过', 0.9);
INSERT INTO reactions (user_id, anchor_id, reaction_type, emotion_word, modality, text_content, resonance_value) VALUES ((SELECT id FROM users WHERE phone_hash='hash_winter'), 'a012', 'resonance', 'empathy', 'text', '深夜的泡面最香', 0.8);
INSERT INTO reactions (user_id, anchor_id, reaction_type, emotion_word, modality, text_content, resonance_value) VALUES ((SELECT id FROM users WHERE phone_hash='hash_night'), 'a013', 'neutral', NULL, 'text', '每个人都在努力', 0.5);
INSERT INTO reactions (user_id, anchor_id, reaction_type, emotion_word, modality, text_content, resonance_value) VALUES ((SELECT id FROM users WHERE phone_hash='hash_dawn'), 'a014', 'resonance', 'trigger', 'text', '失眠的人很多', 0.85);
INSERT INTO reactions (user_id, anchor_id, reaction_type, emotion_word, modality, text_content, resonance_value) VALUES ((SELECT id FROM users WHERE phone_hash='hash_wind'), 'a015', 'resonance', 'insight', 'text', '手机内存确实不够用', 0.78);
